// @ts-nocheck
// Catalogue curé de chaînes gratuites/publiques avec priorité Sport.
exports.LIVE_SEED = [
    // ── Sports (Priorité #1) ────────────────────────────────────────────────
    {
        name: 'beIN SPORTS XTRA',
        slug: 'bein-sports-xtra',
        categories: ['sports'],
        country: 'US',
        language: 'fra',
        streamUrl: 'https://bein-xtra-bein.amagi.tv/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/BeIN_Sports_logo.svg/512px-BeIN_Sports_logo.svg.png',
        aliases: ['bein sports xtra', 'bein xtra', 'bein sport'],
        order: 1,
    },
    {
        name: 'beIN SPORTS XTRA HD',
        slug: 'bein-sports-xtra-hd',
        categories: ['sports'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://bein-xtra-samsungus.amagi.tv/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/BeIN_Sports_logo.svg/512px-BeIN_Sports_logo.svg.png',
        aliases: ['bein sports xtra hd', 'bein sports english'],
        order: 2,
    },
    {
        name: 'Red Bull TV (Sports & Action)',
        slug: 'red-bull-tv',
        categories: ['sports'],
        country: 'FR',
        language: 'fra',
        streamUrl: 'https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Red_Bull_logo.svg/512px-Red_Bull_logo.svg.png',
        aliases: ['red bull tv', 'red bull sports'],
        order: 3,
    },
    {
        name: 'Fight Sports HD',
        slug: 'fight-sports-hd',
        categories: ['sports'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://amg01644-anthem-fntv-samsungus-o2tce.amagi.tv/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Fight_Network_logo.svg/512px-Fight_Network_logo.svg.png',
        aliases: ['fight sports', 'fight network'],
        order: 4,
    },
    {
        name: 'World Poker Tour',
        slug: 'world-poker-tour',
        categories: ['sports', 'entertainment'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://amg00778-amg00778c1-wpt-samsungus-1863.playout.now3.amagi.tv/playlist/amg00778-worldpokertour-wpt-samsungus/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/91/World_Poker_Tour_logo.svg/512px-World_Poker_Tour_logo.svg.png',
        aliases: ['wpt', 'world poker tour'],
        order: 5,
    },
    // ── France & Généraliste ──────────────────────────────────────────────────
    {
        name: 'France 24 Français',
        slug: 'france-24-francais',
        categories: ['news'],
        country: 'FR',
        language: 'fra',
        streamUrl: 'https://static.france24.com/live/F24_FR_LO_HLS/live_web.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/France_24_logo.svg/512px-France_24_logo.svg.png',
        aliases: ['france 24 francais', 'france 24', 'france24'],
        order: 6,
    },
    {
        name: 'TV5MONDE Europe',
        slug: 'tv5monde-europe',
        categories: ['general'],
        country: 'FR',
        language: 'fra',
        streamUrl: 'https://ott.tv5monde.com/Content/HLS/Live/channel(fbs)/variant.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/TV5MONDE_logo.svg/512px-TV5MONDE_logo.svg.png',
        aliases: ['tv5monde europe', 'tv5monde'],
        order: 7,
    },
    {
        name: 'Euronews Français',
        slug: 'euronews-francais',
        categories: ['news'],
        country: 'FR',
        language: 'fra',
        streamUrl: 'https://2f6c5bf4.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmxheHhUVi1ldV9FdXJvbmV3c0ZyYW5jYWlzX0hMUw/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Euronews_2016_logo.svg/512px-Euronews_2016_logo.svg.png',
        aliases: ['euronews francais', 'euronews french'],
        order: 8,
    },
    {
        name: 'LCP Assemblée nationale',
        slug: 'lcp-assemblee-nationale',
        categories: ['politics'],
        country: 'FR',
        language: 'fra',
        streamUrl: 'https://stream.lcp.fr/lcp-direct/live/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/LCP_logo.svg/500px-LCP_logo.svg.png',
        aliases: ['lcp assemblee nationale', 'lcp', 'lcp an'],
        order: 9,
    },
    {
        name: 'Public Sénat',
        slug: 'public-senat',
        categories: ['politics'],
        country: 'FR',
        language: 'fra',
        streamUrl: 'https://fms-publicsenat.yacast.fr/senat-public/live.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/5/52/Logo_Public_S%C3%A9nat_2019.svg/512px-Logo_Public_S%C3%A9nat_2019.svg.png',
        aliases: ['public senat', 'senat public'],
        order: 10,
    },
    // ── International ───────────────────────────────────────────────────────
    {
        name: 'Sky News',
        slug: 'sky-news',
        categories: ['news'],
        country: 'UK',
        language: 'eng',
        streamUrl: 'https://jmp2.uk/plu-55b285cd2665de274553d66f.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Sky_News_logo_2018.svg/512px-Sky_News_logo_2018.svg.png',
        aliases: ['sky news', 'skynews'],
        order: 11,
    },
    {
        name: 'Bloomberg Originals',
        slug: 'bloomberg-originals',
        categories: ['business', 'documentary'],
        country: 'US',
        language: 'eng',
        streamUrl: 'https://86fdc85a.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/TEctZ2JfQmxvb21iZXJnT3JpZ2luYWxzX0hMUw/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Bloomberg_Television_logo.svg/512px-Bloomberg_Television_logo.svg.png',
        aliases: ['bloomberg originals'],
        order: 12,
    },
    {
        name: 'DW English',
        slug: 'dw-english',
        categories: ['news'],
        country: 'DE',
        language: 'eng',
        streamUrl: 'https://amg01644-amg01644c1-amgplt0343.playout.now3.amagi.tv/ts-eu-w1-n2/playlist/amg01644-amg01644c1-amgplt0343/playlist.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Deutsche_Welle_logo.svg/512px-Deutsche_Welle_logo.svg.png',
        aliases: ['dw english', 'deutsche welle english'],
        order: 13,
    },
    {
        name: 'NHK World Japan',
        slug: 'nhk-world-japan',
        categories: ['news'],
        country: 'JP',
        language: 'eng',
        streamUrl: 'https://masterpl.hls.nhkworld.jp/hls/w/live/smarttv.m3u8',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/NHK_World_Japan_2020.svg/512px-NHK_World_Japan_2020.svg.png',
        aliases: ['nhk world japan', 'nhk world', 'nhkworld'],
        order: 14,
    },
    {
        name: 'Al Jazeera English',
        slug: 'al-jazeera-english',
        categories: ['news'],
        country: 'QA',
        language: 'eng',
        streamUrl: 'https://live-hls-web-aje.getaj.net/AJE.m3u8',
        referer: 'https://www.aljazeera.net/',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Al_Jazeera_English_logo.svg/512px-Al_Jazeera_English_logo.svg.png',
        aliases: ['al jazeera english', 'aljazeera english'],
        order: 15,
    },
];
